common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('loin_new/', views.loin_new, name='loin_new'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import home.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('common/', include('common.urls')),
    path('stockManager/', include('stockManager.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path
from . import views

# static 폴더 인식 안될시 사용해 볼 것
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static 폴더 인식 안될시 사용해 볼 것

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/(?<name>)', views.home, name='welcome'),
    path('register/', views.register, name='register'),
]

common/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    """User 에서 사용하기 위한 UserManager 생성"""
    def create_user(self, email, password=None, **extra_fields):
        """일반 유저로 생성할 경우"""
        if not email:
            raise ValueError('이메일을 입력해주세요')

        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """superuser 로 user 를 생성할 경우 필드값을 True 로 변경"""
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """UserManager 를 objects 필드에 사용"""
    CHOICE_GENDER = (
        ('man', '남성'),
        ('woman', '여성')
    )

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    alias = models.CharField(max_length=20, null=True)
    gender = models.CharField(max_length=5, choices=CHOICE_GENDER)
    profile_img = models.ImageField(upload_to='profile', null=True)
    cover_img = models.ImageField(upload_to='cover', null=True)
    introduce = models.TextField(max_length=255)

    # UserManager 을 재정의하여 사용
    objects = UserManager()
    # USERNAME 를 email 로 사용
    USERNAME_FIELD = 'email'

login/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AlembicVersion(models.Model):
    version_num = models.CharField(primary_key=True, max_length=32)

    class Meta:
        managed = False
        db_table = 'alembic_version'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Users(models.Model):
    id = models.CharField(primary_key=True, max_length=20)
    user_name = models.CharField(max_length=100)
    passwd = models.CharField(max_length=100)
    create_date = models.DateTimeField()
    lastupdate_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'users'

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

login/forms.py
from django import forms
from login.models import Users

class UsersForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['id', 'user_name', 'passwd']
        widgets = {
            'id': forms.TextInput(attrs={'class': 'form-control'}),
            'user_name': forms.TextInput(attrs={'class': 'form-control'}),
            'passwd': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'id': '유저 ID',
            'user_name': '표시명',
            'passwd': '비밀번호',
        }

common/views.py
from django.shortcuts import render, redirect
from . import Users

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})


def login(request):
    error = None
    if request.method == 'POST':
        usr_id = request.POST.get('username')
        pw = request.POST.get('password')
        # usr_id = request.form['id']
        # pw = request.form['pw']

        # query the database for the user with the given username and password
        user = Users.objects.get(id=usr_id, passwd=pw)

        if user is not None:
            # redirect the user to the home page
            request.session['login_id'] = user.id
            # redirect_to = reverse('login:welcome', kwargs={'name':user.user_name})
            return redirect('login:welcome', {'user': user})
            # return HttpResponseRedirect(redirect_to)
        else:
            # display an error message
            error = 'Invalid credentials. Please try again.'

        return redirect('common:welcome', {'user': usr_id})

    # render the login page
    return render(request, 'common/login_new.html', {'error': error})

def signup_new(request):
    # if request.method == 'POST':
    #     form = UsersForm(request.POST)
    #     if form.is_valid():
    #         user = form.save(commit=False)
    #         user.create_date = timezone.now()
    #         user.lastupdate_date = timezone.now()
    #         user.save()
    #         return redirect('login:index')
    # else:
    #     form = UsersForm()
    # context = {'form':form}
    # return render(request, 'common/signup.html', context)
    return render(request, 'common/signup.html')


# from django.template import loader
# def exam1(request):
#     template = loader.get_template('exam1.html')
#     # print(template)
#     return HttpResponse(template.render(None, request))

# def exam2(request):
#     template = loader.get_template('exam2.html')
#     context = {'name': 'test', 'address':'서울시'}
#     return HttpResponse(template.render(context, request))
#     # == return render(request, 'exam2.html', context)

login/views.py
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect
from django.utils import timezone
from .models import Users
from .forms import UsersForm

# Create your views here.
def index(request):
    error = None
    if request.method == 'POST':
        usr_id = request.POST.get('id')
        pw = request.POST.get('pw')
        # usr_id = request.form['id']
        # pw = request.form['pw']

        # query the database for the user with the given username and password
        user = Users.objects.get(id=usr_id, passwd=pw)

        if user is not None:
            # redirect the user to the home page
            request.session['login_id'] = user.id
            # redirect_to = reverse('login:welcome', kwargs={'name':user.user_name})
            return redirect('login:welcome', {'user':user})
            # return HttpResponseRedirect(redirect_to)
        else:
            # display an error message
            error = 'Invalid credentials. Please try again.'

    # render the login page
    return render(request, 'login/main.html', {'error' : error})

def home(request, name):
    error = None
    print("++++++++++++++++++++++++++++++++++++++++++++")
    print('name : ', name)

    return render(request, 'login/home.html', {'name':name})

def register(request):
    if request.method == 'POST':
        form = UsersForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.create_date = timezone.now()
            user.lastupdate_date = timezone.now()
            user.save()
            return redirect('login:index')
    else:
        form = UsersForm()
    context = {'form':form}
    return render(request, 'login/register.html', context)

templates/common/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{field.errors}}
    </div>
    {% end if %}
    {% end for %}
    <!-- 넌필드 오류 -->
    {% for error in form.none_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% end for %}
</div>
{% end if %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}

<form method="post" action="{% url 'common:login' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3 mt-3">
        <label for="username">사용자 ID</label>
        <input type="text" class="form-control" name="username" id="username" maxlength="150" value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
        <label for="password">비밀번호</label>
        <input type="password" class="form-control" name="password" id="password" maxlength="150" value="{{ form.password.value|default_if_none:'' }}">
    </div>
    <button type="submit" class="btn btn-primary">로그인</button>
</form>

{% endblock %}

templates/common/login_new.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>{% block title %}login{% endblock %}</title>
</head>
<body>
  <section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
            class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form>
            {% csrf_token %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" name="useremail" id="useremail" class="form-control form-control-lg"
                placeholder="Enter a valid email address" value="{{ form.useremail.value|default_if_none:'' }}"/>
              <label class="form-label" for="useremail">Email address</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password" name="password" id="password" class="form-control form-control-lg"
                placeholder="Enter password" value="{{ form.password.value|default_if_none:'' }}"/>
              <label class="form-label" for="password">Password</label>
            </div>

            <div class="d-flex justify-content-between align-items-center">
              <!-- Checkbox -->
              <div class="form-check mb-0">
                <input class="form-check-input me-2" type="checkbox" value="" id="chk_remember" />
                <label class="form-check-label" for="chk_remember">
                  Remember me
                </label>
              </div>
              <a href="#!" class="text-body">Forgot password?</a>
            </div>

            <div class="text-center text-lg-start mt-4 pt-2">
              <button type="button" class="btn btn-primary btn-lg"
                style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
              <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'login:register' %}"
                  class="link-danger">Register</a></p>
            </div>

          </form>
        </div>
      </div>
    </div>
    <div
      class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
      <!-- Copyright -->
      <div class="text-white mb-3 mb-md-0">
        Copyright © 2020. All rights reserved.
      </div>
    </div>
  </section>
</body>
</html>

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="form-group row">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="col-xs-3">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="col-xs-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="col-xs-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="col-xs-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
    </form>
</div>
{% endblock %}

templates/common/signup_new.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<!DOCTYPE html>
<html lang="en">
<head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>{% block title %}Signin{% endblock %}</title>
</head>
<body>
  <section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
            class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form>
            {% csrf_token %}
            <div class="form-outline mb-3">
              <input type="text" name="username" id="username" class="form-control form-control-lg"
                     placeholder="Enter username" value="{{ form.username.value|default_if_none:'' }}">
              <label class="form-label" for="username">사용자 ID</label>
            </div>


            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password1" name="password1" id="password1" class="form-control form-control-lg"
                placeholder="Enter password" value="{{ form.password1.value|default_if_none:'' }}"/>
              <label class="form-label" for="password1">Password</label>
            </div>

            <div class="form-outline mb-3">
              <input type="password2" name="password1" id="password2" class="form-control form-control-lg"
                placeholder="Confirm password" value="{{ form.password2.value|default_if_none:'' }}"/>
              <label class="form-label" for="password2">Password</label>
            </div>


                        <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" name="useremail" id="useremail" class="form-control form-control-lg"
                placeholder="Enter a valid email address" value="{{ form.useremail.value|default_if_none:'' }}"/>
              <label class="form-label" for="useremail">Email address</label>
            </div>

          </form>
        </div>
      </div>
    </div>
    <div
      class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
      <!-- Copyright -->
      <div class="text-white mb-3 mb-md-0">
        Copyright © 2020. All rights reserved.
      </div>
    </div>
  </section>
</body>
</html>