common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('loin_new/', views.loin_new, name='loin_new'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import home.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('common/', include('common.urls')),
    path('stockManager/', include('stockManager.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

home/urls.py
from django.urls import path
from . import views

# static 폴더 인식 안될시 사용해 볼 것
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static 폴더 인식 안될시 사용해 볼 것

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/(?<name>)', views.home, name='welcome'),
    path('register/', views.register, name='register'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    {% block style %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/base_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    {% block style %}
    {% endblock %}

</head>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<body>
    <div class="topnav">
        <div class="center">
            <div class="menu">
                <!-- 네비게이션바 -->
                {% include "navbar.html" %}
            </div>
        </div>
    </div>

    <div class="sidemenu">
        <!-- 사이드메뉴 -->
        {% include "main_menu.html" %}
    </div>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
    <div class="wrap_content">
        <div id="content" name="content" class="container">
        {% block content %}
        {% endblock %}
        </div>
    </div>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/main_menu.html
<!DOCTYPE html>
<html lang="en">

<style type="text/css">
.submenu {
  display: none;
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1;
  background-color: #fff;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
}

.submenu li {
  display: block;
  margin: 0;
}

.submenu li a {
  display: block;
  padding: 10px;
  color: #333;
  text-decoration: none;
}

.submenu li a:hover {
  background-color: #f5f5f5;
}

</style>
<head>
  <script type="text/javascript">
$(document).ready(function() {
  $.ajax({
    url: '/menu-items/',
    dataType: 'json',
    success: function(data) {
      // Loop through the menu items and create an <li> element for each one
      $.each(data.menu_items, function(index, item) {
        var $li = $('<li><a href="' + item.url + '">' + item.name + '</a></li>');
        // If the menu item has a submenu, create a nested <ul> element for it
        if (item.submenu.length > 0) {
          var $submenu = $('<ul class="submenu"></ul>');
          // Loop through the submenu items and create an <li> element for each one
          $.each(item.submenu, function(index, subitem) {
            $submenu.append('<li><a href="' + subitem.url + '">' + subitem.name + '</a></li>');
          });
          $li.append($submenu);
        }
        $('#menu').append($li);
      });
      // Add a click event listener to the menu items that have a submenu
      $('#menu li:has(".submenu") > a').click(function(e) {
        e.preventDefault();
        $(this).siblings('.submenu').toggle();
      });
    }
  });
});

  </script>
    <meta charset="UTF-8">
    <nav>
      <ul id="menu"></ul>
    </nav>
</head>
<body>

</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'login:index' %}">증권분석</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated%}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>